name: 'Run App'

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.301'
      - name: Install dependencies
      - run: dotnet restore GithubActions.sln
      - name: Build
      - run: msbuild /p:Configuration=Release GithubActions.sln